version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: on-failure
    ports:
      - 80:80
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DOMAIN:-dashboard.localhost}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD}"
  
  maintenance:
    image: wickerlabs/maintenance
    container_name: maintenance
    networks:
      - proxy
    environment:
      TEAM_NAME: "Radya"
      TITLE: "Oops!"
      MAIL_ADDRESS: "email@radya.dev"
      LINK_COLOR: "#dc8100"
      THEME: "Light"
      PORT: 80
      RESPONSE_CODE: "503 Service Unavailable"
      MESSAGE: "This is my custom message. {{contact}} now"
      CONTACT_LINK: "contact us"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maintenance.rule=HostRegexp:{catchall:.*}"
      - "traefik.http.routers.maintenance.entrypoints=web"
      - "traefik.http.routers.maintenance.priority=1"

# NETWORKS
networks:
  proxy:
    external: true